# Generated by Django 5.1.3 on 2024-11-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='column_data',
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
