# Generated by Django 5.1.3 on 2024-11-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addData', '0003_alter_dataentry_id_annotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annotation',
        ),
    ]
