# Generated by Django 5.1.3 on 2024-11-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addData', '0005_annotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataEntry',
        ),
    ]
